# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_order',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
