# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=255)),
                ('years_old', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tur_crm.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_summ', models.FloatField(blank=True, null=True)),
                ('payment_status', models.PositiveIntegerField(choices=[(1, '\u0417\u0430\u0431\u0440\u043e\u043d\u0438\u0440\u043e\u0432\u0430\u043d'), (2, '\u0427\u0430\u0441\u0442\u0438\u0447\u043d\u043e \u043e\u043f\u043b\u0430\u0447\u0435\u043d'), (3, '\u041e\u043f\u043b\u0430\u0447\u0435\u043d')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tur_crm.Client')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PhoneEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tur_crm.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('number_seats', models.PositiveIntegerField()),
                ('number_people', models.PositiveIntegerField()),
                ('data_start', models.DateTimeField()),
                ('data_end', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tur_crm.Tour'),
        ),
    ]
