# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur_crm', '0002_auto_20160624_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
